os: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

install:
  - set C:\Qt\5.15.1\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - ls
  - MSBuild cache-connect.sln /p:Configuration=Release /m
   
after_build: 
  - if not defined APPVEYOR_BUILD_NUMBER (set APPVEYOR_BUILD_NUMBER=%APPVEYOR_BUILD_ID%)
  - cd src\Release
  - mkdir cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy *.exe cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy ..\..\..\LICENSE.md cache-%APPVEYOR_BUILD_NUMBER%
  - 7z a cache-connect-%APPVEYOR_BUILD_NUMBER%-windows.zip cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy cache-connect-%APPVEYOR_BUILD_NUMBER%-windows.zip ..\..\..\
  
artifacts:
  - path: cache-connect-$(APPVEYOR_BUILD_NUMBER)-windows.zip
    name: cache-connect
