os: Visual Studio 2017

environment:
 matrix:
    - PLATFORM: x64
      configuration: Release
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib64-msvc-14.1
      QTDIR: C:\Qt\5.13.2\msvc2017_64
      PATH: '%PATH%;%QTDIR%\bin;%BOOST_ROOT%;%BOOST_LIBRARYDIR%'

install:
  - ps: Start-FileDownload 'http://slproweb.com/download/Win64OpenSSL-1_0_2u.exe'
  - ps: Start-Process "Win64OpenSSL-1_0_2a.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait

build_script:
  - md build
  - cd build
  - ps: 'Write-Host "Running $env:BUILDER with $env:GENERATOR" $env:PLATFORM -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" cmake -G "%GENERATOR%" ..
  - ls
  - MSBuild Cache-Connect.sln /m
   
after_build: 
  - if not defined APPVEYOR_BUILD_NUMBER (set APPVEYOR_BUILD_NUMBER=%APPVEYOR_BUILD_ID%)
  - cd src\Release
  - mkdir cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy *.exe cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy ..\..\..\LICENSE.md cache-%APPVEYOR_BUILD_NUMBER%
  - 7z a cache-connect-%APPVEYOR_BUILD_NUMBER%-windows.zip cache-connect-%APPVEYOR_BUILD_NUMBER%
  - copy cache-connect-%APPVEYOR_BUILD_NUMBER%-windows.zip ..\..\..\
  
artifacts:
  - path: cache-connect-$(APPVEYOR_BUILD_NUMBER)-windows.zip
    name: cache-connect
